#' Scramble Cell Identity and Calculate Scrambled Neighbourhood Expression
#'
#' Internal function that randomly permutes (or resamples) cell identities within a Milo object
#' while preserving the original neighbourhood structure, then recalculates neighbourhood expression.
#'
#' @param milo A Milo object with filled nhoods slot.
#' @param n Integer. Number of permutations or resampling iterations to perform.
#'   Default is 5.
#' @param replace Logical. If \\code{TRUE}, resampling is done with replacement.\n
#'   If \\code{FALSE}, performs a simple permutation without replacement.\n
#'   Default is \\code{FALSE}.\n
#'   Note: if \\code{weight_sample} is provided, \\code{replace} is automatically set to \\code{TRUE}.
#' @param weight_sample A numeric vector of the same length as the number of cells,\n
#'   specifying how likely each cell is to be selected during resampling.\n
#'   If specified, sampling is always done with replacement. Can be generated by\n
#'   \\code{.scramble_calculateWeights()}. Default is \\code{NULL} for uniform weights.
#' @param assay Character string specifying the assay to use for expression values.\n
#'   Default is \"logcounts\".
#'
#' @returns A list of length \\code{n}, where each entry is a matrix of dimensions\n
#'   [n_genes, n_nhoods] containing the neighbourhood expression from scrambled cell assignments.
#'   Format matches \\code{nhoodExpression} from Milo objects.
#'
#' @keywords internal
#' @noRd
.scramble_nhoodExpression <- function(milo,
                                      n = 5,
                                      replace = FALSE,
                                      weight_sample = NULL,
                                      assay = "logcounts") {
  # Returns number of cells in each nhood
  .nhoodSize <- function(milo) {
    out <- Matrix::colSums(nhoods(milo))
    return(out)
  }

  # Permute (or resample) cell gene counts, but keep original nhood structure (number nhoods, size nhoods...)
  mat <- SummarizedExperiment::assay(milo, assay)
  mat_nhoods <- nhoods(milo)
  all_cells <- colnames(milo)
  if (!is.null(weight_sample)) {
    replace <- TRUE
  }
  nhood_sizes <- .nhoodSize(milo)

  l_scrambled_nhoodExpression <- list()
  for (ii in 1:n) {
    permut_cells <- sample(
      all_cells,
      size = length(all_cells),
      replace = replace,
      prob = weight_sample
    )
    permut_mat <- mat[, permut_cells]
    colnames(permut_mat) <- all_cells

    # Average gene expression in permuted nhoods, use consistent matrix format with NhoodExpression
    l_scrambled_nhoodExpression[[ii]] <- permut_mat %*% mat_nhoods
    l_scrambled_nhoodExpression[[ii]] <- l_scrambled_nhoodExpression[[ii]] / rep(nhood_sizes, each =
                                                                                   nrow(l_scrambled_nhoodExpression[[ii]]))
    l_scrambled_nhoodExpression[[ii]] <- as.matrix(l_scrambled_nhoodExpression[[ii]])
  }
  return(l_scrambled_nhoodExpression)
}
